getyoti/yoti-php-sdk

.phpcs.xml
.travis.yml
src/Yoti/Util/Profile/AttributeConverter.php
tests/Util/Profile/AttributeConverterTest.php

- Returning undefined and unknown content types as string
- Logging message when an unknown/undefined content type is returned as string
- Added `.phpcs.xml` and included `/tests/`

SDK-896: Return undefined and unknown content types as string

---

.gitignore
.travis.yml
src/Yoti/Util/Profile/AttributeConverter.php
tests/TestCase.php
tests/Util/Profile/AttributeConverterTest.php

Following #57 I've added test coverage for the logged warnings.
>Note: I'll close this PR if we feel this is unnecessary.

SDK-896: Check log messages are correct

---

.gitignore
.phpcs.xml
.travis.yml
composer.json
config.ini
sandbox/src/Http/SandboxPathManager.php
src/Yoti/Http/AbstractRequestHandler.php
src/Yoti/Util/Profile/AttributeConverter.php
tests/Http/AbstractRequestHandlerTest.php
tests/TestCase.php
tests/Util/Profile/AttributeConverterTest.php

- Prefix version header with SDK identifier
- Return undefined and unknown content types as string

Release 2.2.0: Merge development -> master

---

composer.json
config.ini
examples/composer.json
examples/composer.lock
examples/docker-compose.yml

In #65 I updated the examples to use the local checked out SDK, however, this isn't working correctly outside docker (running `composer install` on host machine)
Composer doesn't allow parent directories as a repository, e.g.
```
"repositories": [
{
"type": "path",
"url": "../",
"options": {
"symlink": true
}
}
],
```
As a result I've changed the implementation to:
- Copy the parent directory into `./examples/sdk` _(excluding `./examples`)_
- `composer.json` will then install the SDK from `./examples/sdk`
>I'd appreciate any suggestions on a more elegant way of implementing `"copy-sdk"` script in `composer.json`
I've also updated the SDK version and the `./examples/composer.lock` to reflect this. 
This should work with both Docker and on host machine:
- `composer update` / `composer …

SDK-1039: Allow composer install without Docker

---

examples/composer.json

> Following #69 
- Ensuring parent directory contains SDK before copying into `./sdk/`
- This only checks that `../composer.json` contains `yoti-php-sdk` - the version is resolved by composer and will only install from `./sdk/` if it's a compatible version.
- Echos _"Could not install SDK from parent directory"_ when the parent directory doesn't contain the SDK, but doesn't fail - this is to allow installation of compatible package on _packagist.org_

SDK-1039: Install example project using local SDK

---

.gitattributes
.gitignore
.php_cs.dist
.phpcs.xml
.phpcs.xml.dist
.travis.yml
CONTRIBUTING.md
composer.json
src/Yoti/Exception/AttributeException.php
src/Yoti/Util/Profile/AnchorConverter.php
tests/Http/RequestSignerTest.php
tests/Util/Age/AgeVerificationConverterTest.php
tests/Util/Profile/AttributeConverterTest.php

- Using [PSR-12](https://www.php-fig.org/psr/psr-12/) (from [PSR-2](https://www.php-fig.org/psr/psr-2/))
- Pre-commit hooks using https://packagist.org/packages/brainmaestro/composer-git-hooks
- `composer test` and `composer lint` scripts to be used by Travis, pre-commit hooks and _CONTRIBUTING.md_
- https://cs.symfony.com/ to allow checks that aren't currently covered by code sniffer:
- No unused imports
- Use short array syntax

SDK-1118: Coding Standards

---

src/Yoti/Http/AbstractRequestHandler.php
src/Yoti/Http/Curl/RequestHandler.php
src/Yoti/Http/CurlRequestHandler.php
src/Yoti/Http/Request.php
src/Yoti/Http/RequestBuilder.php
src/Yoti/Http/RequestHandlerInterface.php
src/Yoti/Http/RequestSigner.php
src/Yoti/Http/Response.php
src/Yoti/YotiClient.php
tests/Http/AbstractRequestHandlerTest.php
tests/Http/Curl/RequestHandlerTest.php
tests/Http/CurlRequestHandlerTest.php
tests/Http/RequestBuilderTest.php
tests/YotiClientTest.php

> Revision of #75 - change log notes below include changes on #75
```php
use Yoti\Http\RequestBuilder;
use Yoti\Http\Payload;
$request = (new RequestBuilder)
->withBaseUrl('https://somehost.com/api/v1')
->withEndpoint('/some-endpoint')
->withPemString($somePemString)
->withMethod('POST')
->withPayload(new Payload(['some' => 'payload']))
->build();
$request->getUrl(); // Returns string
$request->getMethod(); // Returns string
$request->getHeaders(); // Returns associative array of name => value
$request->getPayload(); // Returns \Yoti\Http\Payload
$request->setHandler($handler) // Expects \Yoti\Http\RequestHandlerInterface
$request->execute(); // Executes the request using default (Curl) or custom handler
```
> Note: `Yoti\Http\Payload` is a pre-existing class that also supports payload …

SDK-1080: Signed Request

---

config.ini
sandbox/src/Http/Response.php
sandbox/src/SandboxClient.php
src/Yoti/Http/Curl/RequestHandler.php
tests/Http/AbstractRequestHandlerTest.php

- Sandbox Client now uses new request builder
- Sandbox Client can now use a custom request handler
- `\Yoti\Http\Curl\RequestHandler::setOption()` for customisation per environment

SDK-1183: Allow custom sandbox request handler

---

composer.json

- Composer version
See: https://getcomposer.org/doc/04-schema.md#version
> Note: Packagist uses VCS repositories, so the statement above is very much true for Packagist as well. Specifying the version yourself will most likely end up creating problems at some point due to human error.

SDK-1183: Remove composer version

---

src/Yoti/Http/RequestBuilder.php
tests/Http/RequestBuilderTest.php

- Default `X-Yoti-SDK-Version` header is now `PHP`
- Test coverage for default SDK identifier
- Test coverage for `\Yoti\Http\RequestBuilder::withQueryParam()`

SDK-1195: Correct default SDK identifier

---

src/Yoti/Http/AbstractRequestHandler.php
src/Yoti/Http/RequestBuilder.php
src/Yoti/YotiClient.php
tests/Http/AbstractRequestHandlerTest.php
tests/Http/RequestBuilderTest.php
tests/YotiClientTest.php
tests/config.php

- `X-Yoti-Auth-Key` header is only provided to profile endpoint
- Default `Content-Type` header is only added when payload is provided
- `Yoti\Http\RequestBuilder::YOTI_AUTH_HEADER_KEY`

SDK-1211: Request Builder Headers

---

.travis.yml
README.md
composer.json
tests/Entity/AmlAddressTest.php
tests/Entity/AmlProfileTest.php
tests/Entity/BaseProfileTest.php
tests/Entity/CountryTest.php
tests/Entity/SignedTimestampTest.php
tests/Http/ResponseTest.php

- [Coveralls](https://coveralls.io) to _Travis CI_
- Additional test coverage for:
- `\Yoti\Entity\AmlAddress`
- `\Yoti\Entity\AmlProfile`
- `\Yoti\Entity\Country`
- `\Yoti\Entity\BaseProfile`
- `\Yoti\Http\Response`
- `\Yoti\Entity\SignedTimeStamp`

SDK-1238: Coveralls

---

composer.json
src/Yoti/ShareUrl/Policy/WantedAttribute.php
src/Yoti/ShareUrl/Policy/WantedAttributeBuilder.php
tests/ShareUrl/DynamicScenarioBuilderTest.php
tests/ShareUrl/Policy/DynamicPolicyBuilderTest.php
tests/ShareUrl/Policy/WantedAttributeBuilderTest.php

- Add derivation to payload only when specified
- Pre-commit hook was only failing on exit code of `composer lint` - both `test` and `lint` now need to pass

SDK-1269: Optional Derivation

---

src/Yoti/ShareUrl/Policy/WantedAttribute.php
src/Yoti/Util/Validation.php
tests/ShareUrl/Policy/WantedAttributeBuilderTest.php
tests/Util/ValidationTest.php

- Preventing empty wanted attribute name
- `Validation::notEmptyString()`

SDK-1280: Prevent empty wanted attribute name

---

examples/composer.lock
src/Yoti/Http/Curl/RequestHandler.php
src/Yoti/Http/Response.php
src/Yoti/Util/Validation.php
tests/Http/Curl/RequestHandlerTest.php
tests/Http/ResponseTest.php
tests/Util/ValidationTest.php

- `Yoti\Http\Response::getHeaders()` returns map of response headers
- `Yoti\Util\Validation::isArrayOfStrings()`

SDK-1276: Add headers getter to HTTP response object

---

src/Yoti/Entity/AttributeDefinition.php
src/Yoti/Entity/AttributeIssuanceDetails.php
src/Yoti/ShareUrl/Extension/LocationConstraintExtensionBuilder.php
src/Yoti/ShareUrl/Extension/ThirdPartyAttributeContent.php
src/Yoti/ShareUrl/Extension/ThirdPartyAttributeExtensionBuilder.php
src/Yoti/Util/Constants.php
src/Yoti/Util/ExtraData/ThirdPartyAttributeConverter.php
tests/Entity/AttributeDefinitionTest.php
tests/ShareUrl/Extension/ThirdPartyAttributeContentTest.php
tests/ShareUrl/Extension/ThirdPartyAttributeExtensionBuilderTest.php
tests/Util/EncryptedDataTest.php

- `Yoti\ShareUrl\Extension\ThirdPartyAttributeContent`
- `Yoti\ShareUrl\Extension\ThirdPartyAttributeExtensionBuilder`
- `Yoti\Entity\AttributeDefinition` now implements `\JsonSerializable`
- Global `LOCATION_CONSTRAINT` constant (this should not exist) - `LocationConstraintExtensionBuilder::LOCATION_CONSTRAINT` should be used instead

SDK-1265: Add ThirdPartyAttribute extension

---

tests/ActivityDetailsTest.php
tests/Entity/AnchorTest.php
tests/Entity/AttributeTest.php
tests/Entity/ExtraDataTest.php
tests/Entity/ImageTest.php
tests/Entity/ReceiptTest.php
tests/Util/Profile/AnchorConverterTest.php
tests/Util/Profile/AttributeConverterTest.php

- Added correct `@covers` annotations to tests
- Removed profile unit tests from `YotiTest\ActivityDetailsTest` (covered in `YotiTest\ProfileTest`) - moved test data checks into `::testActivityDetailsInstance()`
- Missing test coverage:
- `YotiTest\Entity\ReceiptTest`
- `::testGetAttribute()`
- `::testGetAttributeNull()`
- `::testGetParentRememberMeId()`
- `::testParseExtraData()`
- `YotiTest\Util\Profile\AttributeListConverterTest`

SDK-1272: Reorganise ActivityDetails unit tests

---

.travis.yml
composer.json
phpunit.xml
tests/Http/Curl/RequestHandlerTest.php
tests/TestCase.php
tests/bootstrap.php

- Travis now runs tests with _PHP 7.4_
- Travis no longer runs tests with _PHP 7.1_
- PHPUnit dev requirement is now `"^5.7 || ^7.5"` ( _PHP 7_ will use `^7.5`)
> Added class alias to support both PHPUnit versions

SDK-1304: PHP 7.4

---

src/YotiClient.php

- Fallback on `$_GET['token']`

SDK-1222: Remove fallback on token GET parameter

---

src/Entity/AmlAddress.php
src/Entity/AmlProfile.php
src/YotiClient.php
tests/Entity/AmlAddressTest.php
tests/Entity/AmlProfileTest.php
tests/Http/CurlRequestHandlerTest.php
tests/Http/PayloadTest.php
tests/Http/RequestSignerTest.php

- `\Yoti\Entity\AmlProfile` now implements `\JsonSerializable`
- `\Yoti\Entity\AmlAddress` now implements `\JsonSerializable`
- `\Yoti\Entity\AmlProfile::getData()`
- `\Yoti\Entity\AmlAddress::getData()`
> Note: `Yoti\Http\Payload` hasn't been updated to implement `\JsonSerializable` as this will be replaced with [PSR-7 implementation](https://www.php-fig.org/psr/psr-7/#34-psrhttpmessagestreaminterface)

SDK-1245: Implement JsonSerializable

---

src/Entity/Anchor.php
tests/Util/Profile/AnchorConverterTest.php
tests/Util/Profile/AnchorListConverterTest.php

- Anchor type is now uppercase `SOURCE`/`VERIFIER`

SDK-988: Uppercase anchor type

---

src/Http/RequestBuilder.php
src/YotiClient.php
tests/Http/RequestBuilderTest.php
tests/YotiClientTest.php

- Hard-coded plugin name validation (now only checks that the provided plugin name is a string)

SDK-1345: Remove plugin name validation

---

.travis.yml

> PHP 7.4 stable was made available since #103: https://changelog.travis-ci.com/php-7-4-is-available-for-linux-builds-129656
- Default test stage uses _PHP 7.4_

SDK-1304: PHP 7.4 stable

---

src/Yoti/ActivityDetails.php
src/Yoti/Exception/DateTimeException.php
src/Yoti/ShareUrl/Extension/ThirdPartyAttributeContent.php
src/Yoti/Util/Constants.php
src/Yoti/Util/DateTime.php
src/Yoti/Util/ExtraData/ThirdPartyAttributeConverter.php
src/Yoti/Util/Profile/AttributeConverter.php
tests/Util/DateTimeTest.php
tests/Util/ExtraData/ThirdPartyAttributeConverterTest.php

- `Yoti\Util\DateTime` used for converting strings to `\DateTime` objects
- `Yoti\Exception\DateTimeException`
- `ThirdPartyAttributeConverter::convertValue()` now uses `Yoti\Util\DateTime::stringToDateTime()`, which supports all `RFC3339` date formats
- `Yoti\Util\Constants::DATE_FORMAT_RFC3339` - replaced by `Yoti\Util\DateTime::RFC3339`

SDK-1364: Fully support RFC3339 date format

---

src/Http/Client.php

- Creating 1 Guzzle client instance per `Yoti\Http\Client` instance

SDK-1374: Re-use Guzzle client

---

src/Aml/Result.php
src/Http/Client.php
src/Http/Exception/ClientException.php
src/Http/Exception/NetworkException.php
src/Http/Exception/RequestException.php
src/Http/RequestBuilder.php
src/Http/RequestSigner.php
tests/Http/ClientTest.php

- Custom exceptions are now passed the previous exception
- `Yoti\Http\Exception\ClientException` implements `\Psr\Http\Client\ClientExceptionInterface`
> Note: this should have been implemented in #107 
- Exception codes using HTTP statuses - these could be misleading

SDK-1376: Exception chaining

---

src/Aml/Address.php
src/Aml/Country.php
src/Aml/Profile.php
tests/Aml/AddressTest.php
tests/Aml/CountryTest.php
tests/Aml/ProfileTest.php

- `\Yoti\Aml\Address`
- `::setCountry()`
- `::setPostcode()`
- `\Yoti\Aml\Country`
- `::setCode()`
- `\Yoti\Aml\Profile`
- `::setGivenNames()`
- `::setFamilyName()`
- `::setSsn()`
- `::setAmlAddress()`

SDK-1380: Remove public setters from AML classes

---

src/Profile/Attribute.php
src/Profile/UserProfile.php
src/Profile/Util/Attribute/AnchorConverter.php
src/Profile/Util/Attribute/AnchorListConverter.php
src/Profile/Util/Attribute/AttributeConverter.php
src/Util/Validation.php
tests/Profile/Attribute/AnchorTest.php
tests/Profile/AttributeTest.php
tests/Profile/ExtraDataTest.php
tests/Profile/UserProfileTest.php
tests/Profile/Util/Attribute/AnchorConverterTest.php
tests/Profile/Util/Attribute/AnchorListConverterTest.php
tests/Util/ValidationTest.php

- `Yoti\Profile\Util\Attribute\AnchorConverter::convert()` now returns `Yoti\Profile\Attribute\Anchor`
- `Yoti\Profile\Util\Attribute\AnchorListConverter::convert()` now returns `Yoti\Profile\Attribute\Anchor[]` _(array)_
- `Yoti\Profile\Attribute` now expects an array of anchors, instead of `array<string, Yoti\Profile\Attribute\Anchor[]>`. This simplifies how anchors are copied to other attributes and also removes the need to process the map into a flat list for `::getAnchors()`
- `Validation::notEmptyString()` now allows any value and throws exception with validation message when a non-string value is provided (this was changed in #127 to only accept string values, which resulted in unfriendly validation messages)

SDK-1382: Simplify anchor converter

---

phpstan.neon.dist

- Removed PHPStan exclusion of `src/Profile/Util/Age/*`, which no longer exists

SDK-1361: Remove PHPStan exclusion

---

src/Media/Exception/InvalidImageTypeException.php

> Amendment to #139 
- `Yoti\Media\Exception\InvalidImageTypeException` (this was added when moving the `Image` object into the `Yoti\Media` namespace, but is no longer used)

SDK-1430: Remove unused exception

---

.gitignore
composer.json
config.ini
examples/composer.lock
sonar-project.properties
src/Yoti/Entity/DocumentDetails.php
tests/Entity/DocumentDetailsTest.php

> Release `2.5.1`
> Back-port of #144 
- Allow any character in DocumentDetails value
> Note: This release will also include non-breaking changes that were deferred to `3.0.0`
> https://github.com/getyoti/yoti-php-sdk/compare/2.5.0..2.x
- Added missing properties to _ExtraData_ classes #128 
- `ThirdPartyAttributeConverter::convertValue()` now uses `Yoti\Util\DateTime::stringToDateTime()`, which supports all `RFC3339` date formats #116 
- `Yoti\Util\DateTime` used for converting strings to `\DateTime` objects
- `Yoti\Exception\DateTimeException`
- `Yoti\Util\Constants::DATE_FORMAT_RFC3339` - replaced by `Yoti\Util\DateTime::RFC3339`

SDK-1446: Document Details Validation

---

sandbox/src/Profile/Request/Attribute/SandboxAgeVerification.php
sandbox/src/Profile/Request/Attribute/SandboxAnchor.php
sandbox/src/Profile/Request/Attribute/SandboxAttribute.php
sandbox/src/Profile/Request/TokenRequest.php
sandbox/src/Profile/Request/TokenRequestBuilder.php
sandbox/tests/Profile/Request/Attribute/SandboxAgeVerificationTest.php
sandbox/tests/Profile/Request/Attribute/SandboxAnchorTest.php
sandbox/tests/Profile/Request/Attribute/SandboxAttributeTest.php
sandbox/tests/Profile/Request/TokenRequestBuilderTest.php
sandbox/tests/Profile/Request/TokenRequestTest.php

- Implemented `JsonSerializable` to replace custom building of JSON data
- Optional flag is now `boolean` throughout instead of `string`
- Removed redundant public getters for JSON serialisable objects _(there is no need to use getters on JSON payload objects)_

SDK-1473: Sandbox Optional Attribute

---

sandbox/src/Profile/Request/Attribute/SandboxAnchor.php
sandbox/tests/Profile/Request/Attribute/SandboxAnchorTest.php
src/Util/DateTime.php
tests/Util/DateTimeTest.php

- Sandbox anchor timestamps are now set using `\DateTime` object
- `Yoti\Util\DateTime::timestampToDateTime()` now supports negative microsecond timestamps

SDK-1475: Use DateTime for sandbox anchor timestamps

---

examples/doc-scan/app/Providers/YotiDocScanServiceProvider.php
examples/doc-scan/config/yoti.php
src/Constants.php
src/DocScan/DocScanClient.php
src/YotiClient.php
tests/DocScan/DocScanClientTest.php
tests/TestCase.php
tests/YotiClientTest.php

- Default API URLs can now be overridden using environment variables:
- `YOTI_API_URL` to override the default API URL
- `YOTI_DOC_SCAN_API_URL` to override the default Doc Scan API URL

SDK-1501: API URL environment variable

---

src/DocScan/Session/Retrieve/CheckResponse.php
src/DocScan/Session/Retrieve/GeneratedCheckResponse.php
src/DocScan/Session/Retrieve/LivenessResourceResponse.php
src/DocScan/Session/Retrieve/ResourceResponse.php
src/DocScan/Session/Retrieve/TaskResponse.php
tests/DocScan/Session/Retrieve/CheckResponseTest.php
tests/DocScan/Session/Retrieve/GetSessionResultTest.php
tests/DocScan/Session/Retrieve/LivenessResourceResponseTest.php
tests/DocScan/Session/Retrieve/ResourceResponseTest.php
tests/DocScan/Session/Retrieve/TaskResponseTest.php
tests/DocScan/Session/Retrieve/ZoomLivenessResourceResponseTest.php
tests/TestCase.php

- `CheckResponse::getType()`
- `TaskResponse::getType()`
- `LivenessResourceResponse::getLivenessType()`
- `GeneratedCheckResponse::getType()`

SDK-1550: Add type to responses

---

src/DocScan/DocScanClient.php
src/Util/Env.php
src/YotiClient.php
tests/DocScan/DocScanClientTest.php
tests/TestCase.php
tests/Util/EnvTest.php
tests/YotiClientTest.php

> Revised #158 
- Read environment variables from `$_SERVER` instead of `getenv`

SDK-1501: Environment Variables

---

src/Aml/Address.php
src/Aml/Country.php
src/Aml/Profile.php
tests/Aml/AddressTest.php
tests/Aml/CountryTest.php
tests/Aml/ProfileTest.php

- Use AML getters for JSON serialisation
- `Country` now implements `\JsonSerializable` and serializes to country code string

SDK-1429: AML JSON serialization

---

phpstan-baseline.neon
phpstan-ignore.neon
phpstan.neon.dist

- Generate PHPStan baseline with default filename using `phpstan analyse --generate-baseline` - see https://phpstan.org/user-guide/baseline (replaces custom filename)
> Note: ignore is added as `ThirdPartyAttribute::getIssuingAttributes()` in the generated protobuf code can technically return `null`

SDK-1346: PHPStan Baseline

---

src/ShareUrl/Extension/ThirdPartyAttributeContent.php
tests/ShareUrl/Extension/ThirdPartyAttributeContentTest.php
tests/ShareUrl/Extension/ThirdPartyAttributeExtensionBuilderTest.php

- Use [`\DateTime::RFC3339_EXTENDED`](https://www.php.net/manual/en/class.datetimeinterface.php#datetime.constants.rfc3339_extended) for 3rd party attribute expiry date

SDK-1586: Use millisecond date format

---

src/Util/Env.php
tests/DocScan/DocScanClientTest.php
tests/Util/EnvTest.php
tests/YotiClientTest.php

- `Yoti\Util\Env::get()` now returns `null` when an environment variable is an empty string
> Note: This is to align with behaviour in other SDKs

SDK-1597: Treat empty env variable strings as null

---

src/Aml/Service.php
src/DocScan/Exception/DocScanException.php
tests/Aml/ServiceTest.php
tests/DocScan/Exception/DocScanExceptionTest.php

- `DocScanException` now includes formatted response error when available
```
Server responded with 400 - PAYLOAD_VALIDATION - There were errors validating the payload: sdk_config.allowed_capture_methods "Value is not valid", sdk_config.font_colour "provided colour must be a valid Hex Code", sdk_config.locale "must not be blank"
```
- `AmlService::performCheck()` will now throw an `AmlException` for non-JSON error responses. Previously, a `JsonException` would be thrown if the SDK was misconfigured with an incorrect API URL that returned non-JSON content.
> Note: `AmlException` messages remain unchanged

SDK-1581: Doc Scan exception message

---

.travis.yml
README.md
src/Profile/Util/Attribute/AttributeListConverter.php
tests/Profile/Util/Attribute/AttributeConverterTest.php
tests/Profile/Util/Attribute/AttributeListConverterTest.php
tests/Profile/Util/ExtraData/ExtraDataConverterTest.php
tests/Profile/Util/ExtraData/ThirdPartyAttributeConverterTest.php

- Travis job to test with [protobuf C extension](https://github.com/protocolbuffers/protobuf/tree/master/php) ([pecl](https://pecl.php.net/package/protobuf)) installed - integrators should install this extension for performance improvements
- No longer mocking protobuf classes _(PHPUnit cannot mock protobuf classes with extension enabled)_
- Attribute converter now skips attributes with name that is `null` or empty string `""`
> Note: it's not possible to create a protobuf attribute with `null` name without mocking, so we could remove this condition. When the name is not set, it will default to an empty string `""`, so skipping when the name is `null` or `""` seemed sensible.
- Exceptions messages are shorter with the extension enabled, so tests have been updated to check for the shorter …

SDK-1628: Protobuf C Extension

---

composer.json
phpunit.xml

- Added `symfony/phpunit-bridge` dev dependency to test deprecation errors.
- Set maximum deprecations threshold to 1 to allow for known deprecation error - see https://github.com/protocolbuffers/protobuf/pull/7629 (marking the related tests as legacy could fix this, but would be misleading). We can remove this configuration if/when this is fixed.

SDK-1627: Check for deprecations

---

composer.json
sonar-project.properties
src/Constants.php
src/DocScan/Session/Create/Check/RequestedCheck.php
src/DocScan/Session/Create/Task/RequestedTask.php
tests/DocScan/Session/Create/Check/RequestedDocumentAuthenticityCheckBuilderTest.php

- `null` check/task config is now omitted from session creation payload

SDK-1676: Omit null check/task config

---

src/Profile/Service.php

- No longer replacing `,` with `=` - this replacement isn't required, has no effect and no other SDK does it - updated to avoid any confusion.

SDK-1673: Correct token decoding

---

examples/aml-check/composer.json
examples/doc-scan/README.md
examples/doc-scan/composer.json
examples/doc-scan/docker-compose.yml
examples/profile/README.md
examples/profile/composer.json
examples/profile/docker-compose.yml

- Updated `composer.json` to install from packagist by default (it will not attempt to copy the SDK to `./sdk/`) - This allows users to copy the example to a different location and install/run without updating `composer.json`
- Added `update-local`/`install-local` commands to update/install using the local SDK
- Docker will continue to install the local SDK using `composer update-local`

SDK-1662: Install demos from packagist by default

---

composer.json

- Use PHPUnit `< 9.3` until coverage reporting is resolved
We can remove this restriction once coverage reporting has been resolved in one of the related issues:
- https://github.com/sebastianbergmann/php-code-coverage/issues/799
- https://community.sonarsource.com/t/php-coverage-uncovered-new-line-at-end-of-file/29888
A ticket has been created to revisit this at a later date

SDK-1724: Fix Test Coverage

---

.travis.yml

Following #188 
- Test compatibility with latest Protobuf C extension (rewrite of 3.12) - see https://github.com/protocolbuffers/protobuf/releases/tag/v3.13.0

SDK-1628: Test with latest Protobuf C extension

---

src/DocScan/Constants.php
src/DocScan/Session/Create/Check/RequestedDocumentAuthenticityCheck.php
src/DocScan/Session/Create/Check/RequestedDocumentAuthenticityCheckBuilder.php
src/DocScan/Session/Create/Check/RequestedDocumentAuthenticityCheckConfig.php
src/DocScan/Session/Create/Check/RequestedFaceMatchCheckBuilder.php
src/DocScan/Session/Create/Task/RequestedTextExtractionTaskBuilder.php
src/DocScan/Session/Create/Traits/Builder/ManualCheckTrait.php
tests/DocScan/Session/Create/Check/RequestedDocumentAuthenticityCheckBuilderTest.php
tests/DocScan/Session/Create/Check/RequestedDocumentAuthenticityCheckConfigTest.php
tests/DocScan/Session/Create/Check/RequestedDocumentAuthenticityCheckTest.php

- `RequestedDocumentAuthenticityCheckBuilder::withManualCheckAlways()`
- `RequestedDocumentAuthenticityCheckBuilder::withManualCheckNever()`
- `RequestedDocumentAuthenticityCheckBuilder::withManualCheckFallback()`
Note: Copied builder trait from #200 which should reduce some duplication

SDK-1737: Document Authenticity check - manual check config

---

src/DocScan/Session/Create/Task/RequestedTextExtractionTaskBuilder.php
src/DocScan/Session/Create/Traits/Builder/ManualCheckTrait.php
tests/DocScan/Session/Create/Check/RequestedFaceMatchCheckBuilderTest.php
tests/DocScan/Session/Create/Task/RequestedTextExtractionTaskBuilderTest.php

Fixes #205 
- Removed public `withManualCheck()` from builder trait (not yet released)
- `RequestedTextExtractionTaskBuilder::withManualCheck()`

SDK-1737: Remove public withManualCheck() from builder trait

---

composer.json
src/Http/Payload.php
tests/Http/PayloadTest.php
tests/YotiClientTest.php

- Replaced uses of `stream_for()` with `Psr7\Utils::streamFor()`

SDK-1797: Replace use of deprecated Guzzle PSR7 functions

---

examples/doc-scan/app/Http/Controllers/HomeController.php
examples/doc-scan/app/Http/Controllers/MediaController.php
src/DocScan/Service.php
tests/Aml/ServiceTest.php
tests/DocScan/Exception/DocScanExceptionTest.php
tests/DocScan/ServiceTest.php
tests/Profile/ServiceTest.php
tests/ShareUrl/ServiceTest.php

- `204` media responses now return `Media` with no content

SDK-1799: Support media responses with no content

---

examples/doc-scan/app/Http/Controllers/HomeController.php
examples/doc-scan/resources/views/privacy.blade.php
examples/doc-scan/routes/web.php
src/DocScan/Session/Create/NotificationConfig.php
src/DocScan/Session/Create/SdkConfig.php
src/DocScan/Session/Create/SdkConfigBuilder.php
tests/DocScan/Session/Create/NotificationConfigBuilderTest.php
tests/DocScan/Session/Create/SdkConfigBuilderTest.php
tests/DocScan/Session/Create/SessionSpecificationBuilderTest.php

- Support for custom privacy policy URL
- `SdkConfig::jsonSerialize()` now omits `null` values and returns object instead of array
- `NotificationConfig::jsonSerialize()` now omits `null` values and returns object instead of array

SDK-1821: Privacy Policy URL

---

.github/dependabot.yml
.github/workflows/sonar.yaml
.github/workflows/tests.yaml
README.md
composer.json
src/Profile/Util/Attribute/AttributeListConverter.php
src/Util/PemFile.php

* SDK-1863: Migrate travis to github actions
* SDK-1863: Remove Travis status from README
* SDK-1863: Add script to generate sonar coverage
* Include "pecl install protobuf-3.13.0" command
When running Protobuf C Extension 3.13 unit tests
* Correct Github Action build status badge
* SDK-1863: Fix type check
* SDK-1863:small fix for php8.0
* SDK-1368: Change protobuf version
* SDK-1368: Trying to install pecl
* SDK-1368: Trying to install pecl
* SDK-1368: Trying to install pecl
* SDK-1368: Trying to install pecl
* SDK-1368: Trying to install pecl
Co-authored-by: Ed Harrod <echarrod@users.noreply.github.com>
Co-authored-by: Rodion Liuborets <rodion.liuborets@yoti.com>

merge master -> development

---

composer.json
src/Http/RequestBuilder.php

Title says it all. This allow the use of the latest versionsof Guzzle PSR7 and the fact to move psr/log to require-dev allow us to not have conflicts while being only used for tests.

Upgraded Guzzle PSR7 to version 2.1.0 and moved psr/log to require-dev

---

README.md
composer.json
examples/profile/app/Http/Controllers/DynamicShareController.php
src/Constants.php
src/Profile/Util/Attribute/AnchorConverter.php
src/Util/Json.php

- ActivityDetails getProfile() function retrieves empty User profile

Sdk 2423 php sdk activity details get profile function retrieves empty user profile

---

examples/digitalidentity/resources/views/advancedidentity.blade.php
examples/doc-scan/app/Http/Controllers/HomeController.php
src/DocScan/Session/Create/SdkConfig.php
src/DocScan/Session/Create/SdkConfigBuilder.php
tests/DocScan/Session/Create/SdkConfigBuilderTest.php

```php
$result = (new SdkConfigBuilder())
->withAllowedCaptureMethod(self::SOME_CAPTURE_METHOD)
->withPrimaryColour(self::SOME_PRIMARY_COLOUR)
->withSecondaryColour(self::SOME_SECONDARY_COLOUR)
->withFontColour(self::SOME_FONT_COLOUR)
->withLocale(self::SOME_LOCALE)
->withPresetIssuingCountry(self::SOME_PRESET_ISSUING_COUNTRY)
->withSuccessUrl(self::SOME_SUCCESS_URL)
->withErrorUrl(self::SOME_ERROR_URL)
->withPrivacyPolicyUrl(self::SOME_PRIVACY_POLICY_URL)
->withAllowHandoff(true)
->withBrandId(self::SOME_BRAND_ID)
->build();
```

SDK-2472-added-php-idv-support-brand-id-in-session-config
