- LICENSE.txt
There's not much to review. I just added the updated terms.
> SDK-52 : Update terms

- composer.json
Just creating a PR to double check this is right
> [SDK-130]: Added license to composer.json file

- example/index.html
- src/Yoti/YotiClient.php
Just creating a PR as I made a small change to an error message wording too
>  [SDK-169]: Updated browser.js reference

- README.md
- also added URL links to Yoti Dashboard when mentioned
> SDK-399: Updated callback URL text

- tests/ActivityDetailsTest.php
- Minor correction to annotation
> SDK-848: Correct unit test annotation

- src/Yoti/Util/Profile/AttributeConverter.php
- tests/Util/Profile/AttributeConverterTest.php
- Handling INT values in `AttributeConverter::convertValueBasedOnContentType()`
> SDK-869: Support INT value

- sandbox/src/Http/SandboxPathManager.php
- Moved sandbox API configuration to pipeline
> SDK-792: Manage sandbox URLs in pipeline

- src/Yoti/Http/AbstractRequestHandler.php
- tests/Http/AbstractRequestHandlerTest.php
- Prefixing version with SDK identifier
- Added test coverage for headers
> SDK-910: Prefix version header with SDK identifier

- src/Yoti/Entity/Anchor.php
- src/Yoti/Entity/ApplicationProfile.php
- src/Yoti/Entity/Profile.php
- `Profile` documentation
- `ApplicationProfile` documentation
- `Anchor` documentation
> SDK-995: Update documentation

- README.md
- Missing code examples:
- Application Profile getters
- Structured Postal Address
- Document Details
> SDK-1050: Update code snippets in README

- .gitignore
- examples/.env.dist
- examples/assets/css/index.css
- examples/assets/css/profile.css
- examples/composer.json
- examples/composer.lock
- examples/docker-compose.yml
- examples/index.php
- examples/profile.inc.php
- examples/profile.php
- Example project now uses modal QR
- Example `composer.json` will now fetch any `2.*` version of the SDK 
- Updated Example lock file with latest stable tag
- Running the Example with `docker-compose` will use the local checked out SDK
- Using official composer Docker container
- Example now supports structured postal address
> SDK-1039: Modal QR

- CONTRIBUTING.md
- _CONTRIBUTING.md_
[> View here](https://github.com/getyoti/yoti-php-sdk/blob/SDK-533-contributing/CONTRIBUTING.md)
> SDK-533: Add CONTRIBUTING.md

- README.md
> SDK-1089: Update dev documentation URL

- config.ini
- src/Yoti/Http/RestRequest.php
> SDK-1184: Use Default Options

- composer.json
> SDK-1118: Fix pre-commit hook

- .gitattributes
- _export-ignore_ for recently added configuration files/directories
> SDK-1372: Update .gitattributes

- src/Yoti/Entity/AttributeDefinition.php
- src/Yoti/Entity/AttributeIssuanceDetails.php
- Added missing properties to _ExtraData_ classes
> SDK-1385: Add missing properties to ExtraData classes

- .travis.yml
- README.md
- sonar-project.properties
- src/Http/RequestBuilder.php
- src/Profile/UserProfile.php
- src/Profile/Util/Attribute/AttributeConverter.php
> SDK-1395: Add sonarcloud analysis

- .travis.yml
> Amendment to #142 
- Running analysis on master
> SDK-1395: SonarCloud

- src/Profile/Attribute/DocumentDetails.php
- tests/Profile/Attribute/DocumentDetailsTest.php
- Allow any character in DocumentDetails value
> SDK-1446: Document Details Validation

- composer.json
- examples/composer.lock
- Moved `ext-json` to `require` in _composer.json_
> SDK-1452: Add ext-json as requirement

- .travis.yml
- composer.json
- examples/composer.lock
> Replaced by Sonar Scanner in #143 
- Removed coveralls composer command
- Removed coveralls coverage stage from Travis
> SDK-1395: Remove Coveralls

- README.md
> SDK-1303: Add link to Doc Scan example

- examples/doc-scan/app/Http/Controllers/ErrorController.php
- examples/doc-scan/resources/views/error.blade.php
- examples/doc-scan/routes/web.php
- Added `/error` page to Doc Scan demo - fix for #153
> SDK-1303: Add Doc Scan demo error page

- examples/doc-scan/.env.example
- examples/doc-scan/config/yoti.php
- Using API URL as base URL for demo iframe
> SDK-1303: Use API URL as iframe base URL

- src/DocScan/DocScanClient.php
- src/YotiClient.php
- Create 1 HTTP client per Yoti client
> SDK-1566: HTTP Client

- examples/doc-scan/.env.example
- Comment out optional environment variables in demo example env file
> NA: Comment out optional environment variables in demo

- examples/doc-scan/README.md
> SDK-1427: Update example README

- .travis.yml
- composer.json
- Updated _guzzlehttp/guzzle_ requirement to `^6.5 || ^7.0`
> SDK-1360: Guzzle 7 Support

- composer.json
- tests/Aml/ServiceTest.php
- tests/DocScan/ServiceTest.php
- tests/Http/RequestBuilderTest.php
- tests/Profile/ServiceTest.php
- tests/ShareUrl/ServiceTest.php
- tests/TestCase.php
- Allow latest PHPUnit to be installed for newer PHP versions
> SDK-1608: Update PHPUnit

- examples/doc-scan/app/Http/Controllers/HomeController.php
- examples/doc-scan/resources/views/success.blade.php
- src/DocScan/Session/Create/Task/RequestedTextExtractionTaskBuilder.php
- src/DocScan/Session/Create/Task/RequestedTextExtractionTaskConfig.php
- src/DocScan/Session/Retrieve/DocumentIdPhotoResponse.php
- src/DocScan/Session/Retrieve/IdDocumentResourceResponse.php
- tests/DocScan/Session/Create/Task/RequestedTextExtractionTaskBuilderTest.php
- tests/DocScan/Session/Create/Task/RequestedTextExtractionTaskConfigTest.php
- tests/DocScan/Session/Retrieve/DocumentFieldsResponseTest.php
- tests/DocScan/Session/Retrieve/DocumentIdPhotoResponseTest.php
- tests/DocScan/Session/Retrieve/FacemapResponseTest.php
- tests/DocScan/Session/Retrieve/FrameResponseTest.php
- tests/DocScan/Session/Retrieve/IdDocumentResourceResponseTest.php
- tests/DocScan/Session/Retrieve/PageInfoTest.php
> SDK-1635: Chip Data

- composer.json
- sonar-project.properties
- src/Constants.php
Bumped minor version to `3.4.0`
> Merge master 3.3.0 > development

- examples/doc-scan/resources/views/home.blade.php
- Updated Doc Scan demo iframe to allow full screen
> SDK-1687: Update Doc Scan demo iframe

- src/DocScan/Constants.php
- src/DocScan/Session/Create/Check/RequestedIdDocumentComparisonCheck.php
- src/DocScan/Session/Create/Check/RequestedIdDocumentComparisonCheckBuilder.php
- src/DocScan/Session/Retrieve/GetSessionResult.php
- src/DocScan/Session/Retrieve/IdDocumentComparisonCheckResponse.php
- tests/DocScan/Session/Create/Check/RequestedIdDocumentComparisonCheckBuilderTest.php
- tests/DocScan/Session/Retrieve/GetSessionResultTest.php
- ID document comparison support
> SDK-1716: ID Document Comparison

- examples/doc-scan/app/Http/Controllers/MediaController.php
- examples/doc-scan/resources/views/success.blade.php
- Face Map is removed from demo
> SDK-1753: Remove Face Map from demo

- examples/doc-scan/resources/views/success.blade.php
- src/DocScan/Session/Create/SessionSpecification.php
- src/DocScan/Session/Create/SessionSpecificationBuilder.php
- src/DocScan/Session/Retrieve/GetSessionResult.php
- tests/DocScan/Session/Create/SessionSpecificationBuilderTest.php
- tests/DocScan/Session/Create/Task/RequestedTextExtractionTaskBuilderTest.php
- tests/DocScan/Session/Retrieve/GetSessionResultTest.php
- Support for biometric consent
> SDK-1744: Biometric Consent

- composer.json
- Update PHPUnit to latest version (coverage reporting has now been fixed)
> SDK-1724: Update PHPUnit

- examples/doc-scan/app/Http/Controllers/HomeController.php
- examples/doc-scan/resources/views/success.blade.php
- examples/docker/Dockerfile
- examples/docker/openssl.cnf
- ID document comparison demo
- Self signed certificate for demo
> SDK-1716: ID Document Comparison Demo

- composer.json
- sonar-project.properties
- src/Constants.php
Bumped minor version to `3.5.0`
> Merge master 3.4.0 → development

- tests/TestCase.php
- Base TestCase is now abstract (fixes [code smell](https://sonarcloud.io/project/issues?id=getyoti%3Aphp&resolved=false&types=CODE_SMELL))
> NA: Abstract TestCase

- .travis.yml
- composer.json
- tests/Http/RequestBuilderTest.php
- tests/Profile/ExtraData/AttributeDefinitionTest.php
- tests/Profile/ExtraData/AttributeIssuanceDetailsTest.php
- tests/ShareUrl/DynamicScenarioBuilderTest.php
- tests/ShareUrl/Policy/DynamicPolicyBuilderTest.php
- tests/ShareUrl/Policy/WantedAttributeBuilderTest.php
- tests/Util/DateTimeTest.php
- Updated `composer.json` to allow installation with PHP 8
- Updated exception unit tests to work across PHP versions
> SDK-1814: Support PHP 8

- .github/dependabot.yml
- Add @LuborRod as reviewer & assignee
> NA: Update dependabot.yml

- src/DocScan/Constants.php
- src/DocScan/Session/Create/NotificationConfig.php
- src/DocScan/Session/Create/NotificationConfigBuilder.php
- tests/DocScan/Session/Create/NotificationConfigBuilderTest.php
Add auth type to notification config
> SDK-1840:Add auth type to notification config
